---
language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
env:
  - DENYWARNINGS=
  - DENYWARNINGS=1
matrix:
  include:
    - rust: nightly
      env: BENCHMARK=1
  allow_failures:
    - rust: beta
    - rust: stable
      env: DENYWARNINGS=1

