[package]
name = "iota_lib_rust"
version = "0.1.0"
authors = ["hekrause <hekrause@htwg-konstanz.de>"]

[dependencies]
tiny-keccak = "1.4.1"
rand = "0.4.1"

[dependencies.iota-mam]
git = "https://github.com/iotaledger/MAM"

[dependencies.iota-curl]
git = "https://github.com/iotaledger/iota.rs"