[package]
name = "iota_lib_rust"
version = "0.1.0"
authors = ["hekrause <hekrause@htwg-konstanz.de>"]

[dependencies]
sha3 = "0.7.2"
rand = "0.4.1"
serde_json = "1.0.8"
reqwest = "0.8.2"
hyper = "0.11.9"
error-chain = "0.11.0"